### ISSUE TITLE
Comments on new tank balance

### ISSUE THREAD

**Issue by jsolson** [raveloda/Coatl-Aerospace#28]
Tagging @jmrd98 

The oscar tank (and maybe the Toroidal - I haven't done the math) is a noteable exception to the otherwise well balanced squad tanks in that it hold far more than it's size would suggest. It's up to you how you want to proceed here. Compared to the oscar the CL-LT80 looks good. Compared to any other tank it holds twice what it should (put it next to an FLT-100). Sometimes you have to take liberties with very small parts so do what feels right.

The MP tank looks good. Squad MP tank dry masses run in the 1/3 to 1/7 fuel mass range. Yours looks like it fits in.

**Comment by raveloda** [comment]
Thank you. I will try and figure out a final something today. If increasing tank capacity will push it away from stock balance, I will likely have to work on the engine. I just don't understand why the disparity is so large

**Comment by jsolson** [comment]
I'm not sure what disparity you mean. Is your intention for the monopropellent tank+engine to have the same deltav as the lfo tank + engine, given the same payload? Really the only thing you do to engines is adjust the mass to set the TWR. 10 on the extreme low end, 30 on the extreme high end.

**Comment by raveloda** [comment]
I will be reducing the monopropellant tank capacity to even it out, rather than increase the LFO tank. I do not need them to be identical, but would like them to be comparable. Monoprop will already be at an advantage due to most probes having an additional built-in supply. I also slightly increased the mp engine mass and reduced its ISP, while slightly reducing the lfo engine mass
